"""Constants shared across the computer module."""

PLATFORM_NAME = "computer"
ROUTE_PREFIX = "/computer"
SUPPORTED_ACTION_TYPES = (
    "click",
    "double_click",
    "right_click",
    "type",
    "press",
    "hotkey",
    "scroll",
    "drag",
    "shell",
    "observe",
)

DEFAULT_COMMAND_TIMEOUT = 20
DEFAULT_MOUSE_DURATION = 0.15
DEFAULT_TYPE_INTERVAL = 0.02
DEFAULT_SCROLL_AMOUNT = 400
DEFAULT_IMAGE_QUALITY = 70
DEFAULT_MAX_IMAGE_WIDTH = 1600
DEFAULT_MAX_IMAGE_HEIGHT = 900
DEFAULT_SAFETY_MODE = "strict"

SCREENSHOT_DIR_ENV = "FRIDAY_COMPUTER_SCREENSHOT_DIR"
COMMAND_TIMEOUT_ENV = "FRIDAY_COMPUTER_COMMAND_TIMEOUT"
IMAGE_QUALITY_ENV = "FRIDAY_COMPUTER_IMAGE_QUALITY"
MAX_IMAGE_WIDTH_ENV = "FRIDAY_COMPUTER_MAX_IMAGE_WIDTH"
MAX_IMAGE_HEIGHT_ENV = "FRIDAY_COMPUTER_MAX_IMAGE_HEIGHT"
ALLOW_SHELL_ENV = "FRIDAY_COMPUTER_ALLOW_SHELL"
SAFETY_MODE_ENV = "FRIDAY_COMPUTER_SAFETY_MODE"
